# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bxMc7l3lWEYwnc3zCYhOulHpvcj0txxn
"""

import pandas as pd

try:
    df = pd.read_csv('/content/Sample - Superstore.csv')
except UnicodeDecodeError:
    df = pd.read_csv('/content/Sample - Superstore.csv', encoding='latin1')
df.head()

print(df.columns)
df.info()

!pip install pandasql
import pandasql as psql

q0 = "SELECT * FROM df LIMIT 5;"
psql.sqldf(q0, locals())

q1 = """
SELECT [Product ID], SUM(Sales) AS TotalRevenue
FROM df
GROUP BY [Product ID]
ORDER BY TotalRevenue DESC
LIMIT 5;
"""
psql.sqldf(q1, locals())

q2 = """
SELECT SUBSTR([Order Date], 1, 4) AS SalesYear, SUM(Sales) AS TotalSales
FROM df
GROUP BY SalesYear
ORDER BY SalesYear;
"""
psql.sqldf(q2, locals())

q3 = """
SELECT Segment, AVG(Sales) AS AvgOrderValue
FROM df
WHERE SUBSTR([Order Date], 1, 4) = '2017'
GROUP BY Segment
ORDER BY AvgOrderValue DESC;
"""
psql.sqldf(q3, locals())

q4 = """
SELECT Country, SUM(Sales) AS TotalCountrySales
FROM df
GROUP BY Country
ORDER BY TotalCountrySales DESC;
"""
psql.sqldf(q4, locals())

df_sorted = df.sort_values('Order Date')
df_sorted['CumulativeSales'] = df_sorted['Sales'].cumsum()
df_sorted[['Order Date', 'CumulativeSales']].head()

result = psql.sqldf(q1, locals())
result.to_csv("/content/top5_products.csv", index=False)